### ISSUE TITLE
“zotfile+链接附件的方式跨平台同步”这个方法不能从pdf中抓取元数据.如果看英文较多的话,有些麻烦

### ISSUE THREAD

**Issue by panyuz** [specter119/RefTools#10]

**Comment by specter119** [comment]
@panyuz 所有同步附件方法，以及Zotero正确插文献的前提，都是已经生成了『常规』的条目，即：
> 确实，同步『文件』附件不需要这些，但是到了文献插入的时，Zotero就无法正常使用了。

* 条目信息完整，至少包括:
  * title
  * year
  * authors
* 文件作为附件，挂到相应的条目上。

zotfile的方法，也不例外，所以，你的问题就转化到，有很多英文的pdf，如果在Zotero中生成『常规』条目。

方法就是，全拖进去，右键从pdf读取元数据。

一般情况下，不太老的英文pdf是基本可以读取元数据的，对于漏网之鱼，再手动用浏览器插件的方法添加。

不过，并不建议这么操作，因为zotero生成条目后很难再更新。读取元数据的方法，是从google学术获取的文献信息，作为一个文摘数据库之一，它很不准。所以，第一次生成条目就尽可能正确，一般从全文数据库用浏览器插件生成条目。

结论一句话，尽量不要用大量pdf直接生成条目，如果必须用，拖进去直接右键读元数据，读不出来的，用浏览器插件补。
