### ISSUE TITLE
软链接后窗口不显示文件夹

### ISSUE THREAD

**Issue by zichunxx** [specter119/RefTools#20]
你好！

我在网上参考了一些和你描述类似的教程，成功将云盘的storage文件夹链接至Zotero目录下，双击Zotero/storage也可以成功跳转至云盘的storage目录。

但是，无论我重启Zotero多少遍，窗口都不显示任何条目。

如果您知道解决办法，还请帮助！

谢谢！

**Comment by specter119** [comment]
zotero 是没法自动导入 pdf 的，你可以看看有没有插件支持。

不是 pdf 放在该放的地方，就会自动有条目出来的。

以及，我不是很推荐 zotero/stroage 软链接出去，我相对更推荐用zotfile+文件链接。

**Comment by zichunxx** [comment]
谢谢您，我学习一下相关教程。

**Comment by specter119** [comment]
客气，我关了，以后有问题还可以提问题问，这个项目不怎么维护了。开个issue回答不多的问题，应该可以。
