### ISSUE TITLE
小问题及其它

### ISSUE THREAD

**Issue by TheKiteRunning** [specter119/RefTools#7]
感谢您的辛苦整理。

在zotero上多出了一个`Scrivener`链接，似乎与主题内容不符合。

另外有两个小建议：
- 软件链接不一定放官网，有些软件可以放特征那个页面，如[citavi](https://www.softhead-citavi.com/features)
- 软件对比可以考虑另做一个表，放置功能对照，打勾即可，这样更加一目了然，如[docear](http://www.docear.org/wp-content/uploads/2014/01/img_52d7b3147574c.png)

顺便说一下我对自己用的几个软件的看法：

- zotero
    + 开源免费
    + 题录及pdf在线获取能力强
    + pdf中可获取题录，书签和标注笔记（中文能力弱）
    + 插件较为丰富
    + 中英文难以混排
    + 附件文件夹杂乱，即便使用zotfile依然不能与软件文件夹结构保持一致
- Docear
    +   开源免费
    +   pdf中的标注与笔记思维导图化，并且可以双向更新
    +   思维导图与pdf原位置支持跳转
    +  思维导图中图片可直接粘贴
- Citavi
    +  强大的题录，网页文字，图片摘取功能（不支持pdf下载）
    + 自带pdf的文字、截图摘取功能
    + 提供Adobe acrobat reader 插件，实现上一条功能
    + 任务管理与提醒功能
    + 方便的引用和笔记功能
    + 有中文官网
- NoteExpress
    + 可以获取题录与pdf（pdf只是下载而不是绑定到文献）
    + pdf中获取题录并自动更新
    + 强大的pdf下载功能
    + 中英文混排
    + pdf文件夹与软件文件夹结构保持一致

**Comment by specter119** [comment]
@TheKiteRunning 谢谢提供建议，Scrivener这个是准备以后补充的。
但是docear那个表，我感觉维护起来麻烦，实用性不强，如果有需要，可以专门做一页，或者直接外链一个wiki，就不用维护了。
剩下的，我只是想尽可能的挖好坑，等慢慢有人来填，我自己可能就能照顾到zotero一点了的。
至于您后面的看法，我只能说，主页不添加太多过多的评价，和填表形式一样，且容易加入主观色彩。
